version: "2.4"

services:

  # Administrator: http://127.0.0.1:8080/CFIDE/administrator/index.cfm
  cfml:
    build:
      context: "./app/docker/"
      dockerfile: "Dockerfile"
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      APP_DIR: "/app/wwwroot"
      BOX_SERVER_APP_CFENGINE: "adobe@2021.0.13+330286"
      BOX_SERVER_PROFILE: "development"
      CFPM_INSTALL: "debugger"

  client:
    build:
      context: "./app/client/main/build/docker/"
      dockerfile: "Dockerfile"
    image: "app.featureflagsbook.com/client:latest"
    command: [ "npm", "run", "build" ]
    volumes:
      - "./app/client/main/build:/app"
      # Mount the ColdFusion app for collocation of client files with the CFML views.
      - "./app/client/common:/app/src/cfml-common"
      - "./app/client/main:/app/src/cfml-main"
      # Save dist files into CFML volume where they can be consumed by the app.
      - "./app/wwwroot/client/main:/app/dist"
      # Makes sure we don't overwrite the node_modules in the build container.
      - "client_node_modules:/app/node_modules"

  client-dev:
    extends: "client"
    profiles:
      - "dev"
    command: [ "npm", "run", "watch" ]

volumes:
  client_node_modules:
