version: "2.4"

services:

  # Administrator: http://127.0.0.1:8080/CFIDE/administrator/index.cfm
  cfml:
    image: "ortussolutions/commandbox:latest"
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      APP_DIR: "/app/wwwroot"
      BOX_SERVER_APP_CFENGINE: "adobe@2021.0.13+330286"
      BOX_SERVER_PROFILE: "development"
      CFPM_INSTALL: "debugger"

  # This service will build the distribution files into the CFML app volume, and then
  # stop. For active development, use the ng-internal-dev service.
  ng-internal:
    build:
      context: "./ng-internal/"
      dockerfile: "Dockerfile"
    image: "app.featureflagsbook.com/ng-internal:latest"
    command: [ "npm", "run", "build" ]
    volumes:
      - "./ng-internal:/app"
      - "./app/wwwroot/ng/internal:/app/dist" # Save dist files into CFML volume.
      - "ng_internal_node_modules:/app/node_modules"

  # When actively developing the ng-internal code, this service overrides the command and
  # enables watch mode. Note that this creates a different container that will need to be
  # removed manually.
  ng-internal-dev:
    extends: "ng-internal"
    command: [ "npm", "run", "watch" ]

# Using docker volumes to manage node_modules can help with performance.
volumes:
  ng_internal_node_modules:
