version: "2.4"

services:

  # Administrator: http://127.0.0.1:8080/CFIDE/administrator/index.cfm
  cfml:
    image: "ortussolutions/commandbox:latest"
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      APP_DIR: "/app/wwwroot"
      BOX_SERVER_APP_CFENGINE: "adobe@2021.0.13+330286"
      BOX_SERVER_PROFILE: "development"
      CFPM_INSTALL: "debugger"

  client-playground:
    build:
      context: "./client/playground/"
      dockerfile: "Dockerfile"
    image: "app.featureflagsbook.com/client/playground:latest"
    command: [ "npm", "run", "build" ]
    volumes:
      - "./client/playground:/app"
      - "./app/wwwroot/client/playground:/app/dist" # Save dist files into CFML volume.
      - "client_playground_node_modules:/app/node_modules"

  client-playground-dev:
    extends: "client-playground"
    profiles:
      - "dev"
    command: [ "npm", "run", "watch" ]

# Using docker volumes to manage node_modules can help with performance.
volumes:
  client_playground_node_modules:
  ng_internal_node_modules:
